name: WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validation Check (Debug)
        run: |
          if grep -q "" README.md && grep -q "" README.md; then
            echo "✅ Etiquetas encontradas correctamente en el README."
          else
            echo "❌ ERROR: No se encontraron las etiquetas o "
            echo "Asegúrate de que no tengan espacios extras y que el SECTION_NAME sea 'waka'."
            exit 1
          fi

      - name: Update Waka Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          BLOCKS: █
